name: "weather_dbt"
version: "1.0.0"
config-version: 2

profile: "weather_dbt"

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  weather_dbt:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
